# Generated by Django 5.2.3 on 2025-09-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallerry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallerry',
            new_name='ProductGallery',
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
