# Generated by Django 5.2.3 on 2025-10-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
