# Generated by Django 5.2.3 on 2025-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
