# Generated by Django 5.2.3 on 2025-10-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_payment_status_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='REDXConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('sandbox_base_url', models.CharField(default='https://sandbox.redx.com.bd/v1.0.0-beta', max_length=255)),
                ('sandbox_token', models.TextField()),
                ('production_base_url', models.CharField(default='https://openapi.redx.com.bd/v1.0.0-beta', max_length=255)),
                ('production_token', models.TextField()),
                ('store_name', models.CharField(default='Your Store Name', max_length=255)),
                ('store_phone', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('store_address', models.TextField(default='Your Store Address')),
                ('store_area', models.CharField(default='Dhaka', max_length=100)),
                ('store_district', models.CharField(default='Dhaka', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'REDX Configuration',
                'verbose_name_plural': 'REDX Configurations',
            },
        ),
        migrations.CreateModel(
            name='REDXParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('customer_area', models.CharField(max_length=100)),
                ('customer_district', models.CharField(max_length=100)),
                ('parcel_weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=6)),
                ('cash_collection_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('picked', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('redx_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redx_parcel', to='orders.order')),
            ],
            options={
                'verbose_name': 'REDX Parcel',
                'verbose_name_plural': 'REDX Parcels',
                'ordering': ['-created_at'],
            },
        ),
    ]
