# Generated by Django 5.2.3 on 2025-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_missing_orderproduct_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Paid (Delivery Charge)', 'Paid (Delivery Charge)'), ('Refunded', 'Refunded')], default='Unpaid', help_text='Track payment progress (editable by admin).', max_length=30),
        ),
    ]
