# Generated by Django 5.2.3 on 2025-10-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid (Full)', 'Paid (Full)'), ('Paid (Delivery Charge)', 'Paid (Delivery Charge)'), ('Refunded', 'Refunded')], default='Unpaid', help_text='Track payment progress (editable by admin).', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid (Delivery Charge)', 'Paid (Delivery Charge)'), ('Paid (Full)', 'Paid (Full)'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Pending', max_length=100),
        ),
    ]
