# Generated by Django 5.2.3 on 2025-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_advance_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('nagad_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('rocket_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='requires_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('ADVANCE', 'Advance Payment')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'Bkash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
