# Generated by Django 5.2.3 on 2025-10-04 05:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, help_text='Area/locality within district', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be collected from customer (Total - Online Payment)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
