# Generated by Django 5.2.3 on 2025-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentsettings_order_requires_advance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City/Location name', max_length=100, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Delivery charge for this location', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default charge for unlisted locations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charges',
                'ordering': ['location'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
