# Generated by Django 5.2.3 on 2025-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliverycharge_remove_order_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='advance_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('ADVANCE', 'Delivery Charge Only')], default='FULL', max_length=10),
        ),
    ]
