# Generated by Django 5.2.3 on 2025-09-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='area',
        ),
    ]
