# Generated by Django 5.2.3 on 2025-09-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_city_order_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='area',
            new_name='city',
        ),
    ]
